app = "englishm-moq-relay"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
PORT = "4443"

[experimental]
cmd = "./fly-relay.sh"

[[services]]
internal_port = 4443
protocol = "udp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
port = "4443"
